name: Build and push ComfyUI target image to GHCR

on:
  push:
    branches: [ "master" ]
    paths:
      - "Dockerfile.comfyui"
      - ".github/workflows/build-and-push-target.yml"
      
  workflow_dispatch:
    inputs:
      cuda_version:
        description: "Override CUDA version (e.g. cu128)"
        required: true
        default: "cu128"
      comfyui_version:
        description: "Override ComfyUI version (e.g. v0.3.40)"
        required: false
        default: "v0.3.40"
      torch_version:
        description: "Override PyTorch version (e.g. 2.7.1)"
        required: false
        default: "2.7.1"
      torchaudio_version:
        description: "Override Torchaudio version (e.g. 2.7.1)"
        default: "2.7.1"
        required: false
      torchvision_version:
        description: "Override Torchaudio version (e.g. 0.22.1)"
        default: "0.22.1"
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  CUDA_TAG: cu128
  CUDA_VERS: 12.8.1
  # Use workflow-dispatch input if provided, otherwise fall back to default
  COMFYUI_VERSION: ${{ github.event.inputs.comfyui_version || 'v0.3.40' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CUDA_TAG: ${{ github.event.inputs.cuda_version || 'cu128' }}
      TORCH_VERSION: ${{ github.event.inputs.torch_version || '2.7.1' }}
      TORCHAUDIO_VERSION: ${{ github.event.inputs.torchaudio_version || '2.7.1' }}
      TORCHVISION_VERSION: ${{ github.event.inputs.torchvision_version || '0.22.1' }}
      COMFYUI_VERSION: ${{ github.event.inputs.comfyui_version || 'v0.3.40' }}
      
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch emulation)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "linux/amd64,linux/arm64"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------------------------------------------------------------------
      # Optional: Log in to Docker Hub if credentials are provided.  Requires
      # DOCKERHUB_USERNAME and DOCKERHUB_TOKEN repository secrets.
      # Uncomment to enable Docker Hub pushes.
      # -------------------------------------------------------------------
      # - name: Log in to Docker Hub
      #   if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != ''
      #   uses: docker/login-action@v3
      #   with:
      #     registry: docker.io
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Wait for base image to be available
        timeout-minutes: 20
        run: |
          echo "Waiting for base image: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/torch-base:${{ env.TORCH_VERSION }}-${{ env.CUDA_TAG }}"
          until docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/torch-base:${{ env.TORCH_VERSION }}-${{ env.CUDA_TAG }} &> /dev/null
          do
            echo "Base image not yet available. Waiting 30 seconds..."
            sleep 30
          done
          echo "Base image found. Proceeding with the build."

      # -------------------------------------------------------------------
      # Build & push the final ComfyUI runtime image.
      # -------------------------------------------------------------------
      - name: Build & push ComfyUI image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.comfyui
          build-args: |
            CUDA_TAG=${{ env.CUDA_TAG }}
            CUDA_VERS=${{ env.CUDA_VERS }}
            TORCH_VERSION=${{ env.TORCH_VERSION }}
            TORCHAUDIO_VERSION=${{ env.TORCHAUDIO_VERSION }}
            TORCHVISION_VERSION=${{ env.TORCHVISION_VERSION }}
            COMFYUI_VERSION=${{ env.COMFYUI_VERSION }}
          # no space between platforms, only build amd64 for now
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          # Push to GitHub Container Registry (GHCR)
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/comfyui-docker:${{ env.COMFYUI_VERSION }}-torch${{ env.TORCH_VERSION }}-${{ env.CUDA_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/comfyui:${{ env.COMFYUI_VERSION }}-torch${{ env.TORCH_VERSION }}-${{ env.CUDA_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/comfyui-docker:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/comfyui:latest
          labels: |
            org.opencontainers.image.description=ComfyUI ${{ env.COMFYUI_VERSION }} image (amd64, arm64) with Torch ${{ env.TORCH_VERSION }} and CUDA ${{ env.CUDA_TAG }} runtime. Includes NVIDIA CUDA Toolkit components - see https://docs.nvidia.com/cuda/eula/index.html
